# Generated by Django 5.2.15 on 2026-06-13 15:08

import apps.reservations.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
        ('gardens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The ExclusionConstraint below uses a GiST index over (garden, tstzrange);
        # btree_gist lets a GiST index hold the scalar garden FK alongside the range
        # (PLAN 7.4.2). Must run before the constraint is added.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dogs_count', models.PositiveSmallIntegerField(default=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending_payment', 'Oczekuje na płatność'), ('awaiting_host', 'Oczekuje na decyzję gospodarza'), ('confirmed', 'Potwierdzona'), ('rejected', 'Odrzucona'), ('cancelled', 'Anulowana')], db_index=True, default='pending_payment', max_length=20)),
                ('price_per_hour_snapshot', models.DecimalField(decimal_places=2, max_digits=7)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('message_to_host', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='dogs.dog')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='gardens.garden')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['garden', 'start_time'], name='reservation_garden_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='reservation_end_after_start'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['awaiting_host', 'confirmed'])), expressions=[('garden', '='), (apps.reservations.models.TsTzRange(models.F('start_time'), models.F('end_time'), django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='reservation_no_overlap')],
            },
        ),
    ]
