/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/login/ — e-mail + password to a token pair (anti-bruteforce throttled). */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/logout/ — blacklist the supplied refresh token. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/password/reset/ — e-mail a reset link (always 200, no enumeration). */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/password/reset/confirm/ — set a new password from a reset token. */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /auth/refresh/ — rotate the refresh token and issue a new access token.
         *
         *     Rotation + blacklist-after-rotation are configured in ``SIMPLE_JWT`` (PLAN AD-3),
         *     so a rotated (old) refresh token is rejected on reuse.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/register/ — create a client/host account and return tokens + profile. */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dogs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /dogs/ — the logged-in client's dogs; POST /dogs/ — add a dog. */
        get: operations["dogs_list"];
        put?: never;
        /** @description GET /dogs/ — the logged-in client's dogs; POST /dogs/ — add a dog. */
        post: operations["dogs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dogs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/PATCH/DELETE /dogs/{id}/ — only the owner's own dog (others → 404). */
        get: operations["dogs_retrieve"];
        put?: never;
        post?: never;
        /** @description GET/PATCH/DELETE /dogs/{id}/ — only the owner's own dog (others → 404). */
        delete: operations["dogs_destroy"];
        options?: never;
        head?: never;
        /** @description GET/PATCH/DELETE /dogs/{id}/ — only the owner's own dog (others → 404). */
        patch: operations["dogs_partial_update"];
        trace?: never;
    };
    "/api/v1/dogs/{id}/photo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /dogs/{id}/photo/ — upload (compress + store) the dog's avatar. */
        post: operations["dogs_photo_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /gardens/ — public catalogue of approved, active gardens with filters/sort. */
        get: operations["gardens_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /gardens/{id}/ — public detail; owner/admin may also open their pending garden. */
        get: operations["gardens_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{id}/availability/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /gardens/{id}/availability/?date=YYYY-MM-DD — hourly slot map for a day. */
        get: operations["gardens_availability_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Liveness/readiness probe used by the Docker healthcheck.
         *
         *     Returns 200 only when the database and Redis are reachable, 503 otherwise.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/gardens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /host/gardens/ — the host's gardens (any status); POST — create one (pending). */
        get: operations["host_gardens_list"];
        put?: never;
        /** @description GET /host/gardens/ — the host's gardens (any status); POST — create one (pending). */
        post: operations["host_gardens_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/gardens/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/PATCH/DELETE /host/gardens/{id}/ — manage one of the host's own gardens. */
        get: operations["host_gardens_retrieve"];
        put?: never;
        post?: never;
        /** @description GET/PATCH/DELETE /host/gardens/{id}/ — manage one of the host's own gardens. */
        delete: operations["host_gardens_destroy"];
        options?: never;
        head?: never;
        /** @description GET/PATCH/DELETE /host/gardens/{id}/ — manage one of the host's own gardens. */
        patch: operations["host_gardens_partial_update"];
        trace?: never;
    };
    "/api/v1/host/gardens/{id}/photos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /host/gardens/{id}/photos/ — upload (compress + store) a gallery photo. */
        post: operations["host_gardens_photos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/gardens/{id}/photos/{photo_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description DELETE /host/gardens/{id}/photos/{photoId}/ — remove a gallery photo. */
        delete: operations["host_gardens_photos_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/gardens/{id}/photos/reorder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description PATCH /host/gardens/{id}/photos/reorder/ — set gallery order (cover first). */
        patch: operations["host_gardens_photos_reorder_partial_update"];
        trace?: never;
    };
    "/api/v1/host/reservations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /host/reservations/ — reservations on the host's gardens (paid only). */
        get: operations["host_reservations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/reservations/{id}/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /host/reservations/{id}/accept/ — ``awaiting_host → confirmed`` + e-mail. */
        post: operations["host_reservations_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/reservations/{id}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /host/reservations/{id}/reject/ — ``awaiting_host → rejected`` + refund + e-mail. */
        post: operations["host_reservations_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/schedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /host/schedule/?from=&to=&garden= — committed reservations as calendar events. */
        get: operations["host_schedule_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /host/stats/ — dashboard tiles (counts, earnings, average rating). */
        get: operations["host_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /me/ — read, update, or deactivate (GDPR) the logged-in account. */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        /** @description /me/ — read, update, or deactivate (GDPR) the logged-in account. */
        delete: operations["me_destroy"];
        options?: never;
        head?: never;
        /** @description /me/ — read, update, or deactivate (GDPR) the logged-in account. */
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/v1/me/password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description PATCH /me/password/ — change password while authenticated. */
        patch: operations["me_password_partial_update"];
        trace?: never;
    };
    "/api/v1/reservations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /reservations/ — the client's own bookings; POST — create one (pending_payment). */
        get: operations["reservations_list"];
        put?: never;
        /** @description GET /reservations/ — the client's own bookings; POST — create one (pending_payment). */
        post: operations["reservations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /reservations/{id}/ — detail for a participant (client or the garden's host). */
        get: operations["reservations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /reservations/{id}/cancel/ — client cancels; response carries ``refunded``. */
        post: operations["reservations_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /reservations/export.csv — the client's reservations as a CSV download. */
        get: operations["reservations_export.csv_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `pool` - Basen dla psów
         *     * `water` - Woda i miski
         *     * `shelter` - Wiata / schronienie
         *     * `lighting` - Oświetlenie wieczorne
         *     * `parking` - Parking
         *     * `agility` - Tor agility
         *     * `bench` - Ławki dla opiekuna
         *     * `bin` - Kosze na odchody
         *     * `fenced_secure` - Pełne ogrodzenie 1,8 m
         *     * `shade` - Naturalny cień / drzewa
         * @enum {string}
         */
        AmenitiesEnum: "pool" | "water" | "shelter" | "lighting" | "parking" | "agility" | "bench" | "bin" | "fenced_secure" | "shade";
        /** @description Response shape for register/login: token pair plus the user profile. */
        AuthTokens: {
            readonly access: string;
            readonly refresh: string;
            readonly user: components["schemas"]["User"];
        };
        /** @description Daily availability map for a garden (PLAN 8.3). */
        Availability: {
            /** Format: date */
            date: string;
            /** Format: time */
            open_from: string;
            /** Format: time */
            open_to: string;
            slots: components["schemas"]["Slot"][];
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /** @description Cancel response: the refund outcome plus the updated reservation (PLAN 8.2). */
        CancelResult: {
            refunded: boolean;
            reservation: components["schemas"]["ReservationDetail"];
        };
        /** @description Public-facing client identity shown to the host on a reservation. */
        ClientMini: {
            readonly id: number;
            readonly full_name: string;
        };
        /** @description Generic ``{"detail": "..."}`` response. */
        Detail: {
            readonly detail: string;
        };
        /** @description Full read shape of a dog. ``DogListSerializer`` narrows the field set. */
        DogDetail: {
            readonly id: number;
            readonly name: string;
            readonly breed: string;
            /** Format: date */
            readonly birth_date: string | null;
            readonly age_label: string | null;
            /** Format: decimal */
            readonly weight_kg: string | null;
            readonly sex: components["schemas"]["SexEnum"];
            readonly is_sterilized: boolean;
            /** Format: date */
            readonly vaccinations_valid_until: string | null;
            readonly vaccinations_status: string;
            /** Format: date */
            readonly deworming_valid_until: string | null;
            readonly deworming_status: string;
            readonly health_status: string;
            readonly notes: string;
            /** Format: uri */
            readonly photo: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Lighter shape for the "Moi pupile" list (drops free-text and audit fields). */
        DogList: {
            readonly id: number;
            readonly name: string;
            readonly breed: string;
            readonly age_label: string | null;
            /** Format: decimal */
            readonly weight_kg: string | null;
            readonly sex: components["schemas"]["SexEnum"];
            readonly is_sterilized: boolean;
            readonly vaccinations_status: string;
            readonly deworming_status: string;
            readonly health_status: string;
            /** Format: uri */
            readonly photo: string | null;
        };
        /** @description Compact dog card embedded in a reservation. */
        DogMini: {
            readonly id: number;
            readonly name: string;
            readonly breed: string;
        };
        /** @description Multipart photo upload for a dog (PLAN 8.2). Heavy validation happens on processing. */
        DogPhoto: {
            /** Format: uri */
            photo: string;
        };
        /** @description Validate dog input on create/update. ``owner`` and ``photo`` are set elsewhere. */
        DogWrite: {
            name: string;
            breed?: string;
            /** Format: date */
            birth_date?: string | null;
            /** Format: decimal */
            weight_kg?: string | null;
            sex?: components["schemas"]["SexEnum"] | components["schemas"]["BlankEnum"];
            is_sterilized?: boolean;
            /** Format: date */
            vaccinations_valid_until?: string | null;
            /** Format: date */
            deworming_valid_until?: string | null;
            notes?: string;
        };
        /** @description Full garden view: gallery, public host, amenity labels, rules, rating. */
        GardenDetail: {
            readonly id: number;
            readonly title: string;
            readonly description: string;
            readonly city: string;
            readonly address: string;
            /** Format: decimal */
            readonly latitude: string;
            /** Format: decimal */
            readonly longitude: string;
            readonly area_m2: number;
            readonly surface_type: components["schemas"]["SurfaceTypeEnum"];
            readonly is_fenced: boolean;
            /** Format: decimal */
            readonly fence_height_m: string | null;
            readonly max_dogs: number;
            /** Format: decimal */
            readonly price_per_hour: string;
            /** Format: time */
            readonly open_from: string;
            /** Format: time */
            readonly open_to: string;
            readonly min_booking_hours: number;
            readonly amenities: unknown;
            /** @description Resolve stored amenity codes to ``{code, label}`` (label catalogue lives in BE). */
            readonly amenities_display: {
                [key: string]: unknown;
            }[];
            readonly rules: unknown;
            readonly verification_status: components["schemas"]["VerificationStatusEnum"];
            readonly rejection_reason: string;
            readonly is_active: boolean;
            readonly host: components["schemas"]["HostPublic"];
            readonly photos: components["schemas"]["GardenPhoto"][];
            /** Format: double */
            readonly rating_avg: number | null;
            readonly rating_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Light catalogue/map card: cover thumbnail, location, price, rating. */
        GardenList: {
            readonly id: number;
            readonly title: string;
            readonly city: string;
            readonly address: string;
            /** Format: decimal */
            readonly latitude: string;
            /** Format: decimal */
            readonly longitude: string;
            readonly area_m2: number;
            readonly surface_type: components["schemas"]["SurfaceTypeEnum"];
            readonly max_dogs: number;
            /** Format: decimal */
            readonly price_per_hour: string;
            readonly cover_image: string | null;
            /** Format: double */
            readonly rating_avg: number | null;
            readonly rating_count: number;
        };
        /** @description Compact garden card embedded in a reservation (PLAN 8.3). */
        GardenMini: {
            readonly id: number;
            readonly title: string;
            readonly city: string;
            /** Format: decimal */
            readonly price_per_hour: string;
            readonly cover_image: string | null;
        };
        /** @description Read shape of a gallery photo (URLs are absolute when a request is in context). */
        GardenPhoto: {
            readonly id: number;
            /** Format: uri */
            readonly image: string;
            /** Format: uri */
            readonly thumbnail: string;
            readonly position: number;
        };
        /** @description Multipart photo upload for a garden (PLAN 8.2). Heavy validation happens on processing. */
        GardenPhotoUpload: {
            /** Format: uri */
            image: string;
        };
        /** @description Validate garden create/update. ``host``/status/photos are set elsewhere (PLAN 8.2). */
        GardenWrite: {
            title: string;
            description?: string;
            city: string;
            address: string;
            /** Format: decimal */
            latitude: string;
            /** Format: decimal */
            longitude: string;
            area_m2: number;
            surface_type?: components["schemas"]["SurfaceTypeEnum"] | components["schemas"]["BlankEnum"];
            is_fenced?: boolean;
            /** Format: decimal */
            fence_height_m?: string | null;
            max_dogs?: number;
            /** Format: decimal */
            price_per_hour: string;
            /** Format: time */
            open_from?: string;
            /** Format: time */
            open_to?: string;
            min_booking_hours?: number;
            amenities?: components["schemas"]["AmenitiesEnum"][];
            rules?: string[];
            is_active?: boolean;
        };
        HealthResponse: {
            status: string;
            db: boolean;
            redis: boolean;
        };
        /** @description Public-facing host identity shown on a garden detail page. */
        HostPublic: {
            readonly id: number;
            readonly full_name: string;
            readonly is_verified_host: boolean;
        };
        /** @description Host dashboard tiles (PLAN 8.2). */
        HostStats: {
            pending_count: number;
            upcoming_count: number;
            completed_count: number;
            /** Format: decimal */
            total_earnings: string;
            /** Format: double */
            rating_avg: number | null;
        };
        /** @description E-mail + password login; embeds the user profile and a ``role`` claim in the token. */
        Login: {
            email: string;
            password: string;
        };
        /** @description Refresh token to blacklist on logout. */
        Logout: {
            refresh: string;
        };
        PaginatedDogListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DogList"][];
        };
        PaginatedGardenListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["GardenList"][];
        };
        PaginatedReservationListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ReservationList"][];
        };
        /** @description Set a new password using the token from the reset e-mail. */
        PasswordResetConfirm: {
            uid: string;
            token: string;
            new_password: string;
            new_password_confirm: string;
        };
        /** @description Request a reset link for an e-mail address. */
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        /** @description Validate dog input on create/update. ``owner`` and ``photo`` are set elsewhere. */
        PatchedDogWrite: {
            name?: string;
            breed?: string;
            /** Format: date */
            birth_date?: string | null;
            /** Format: decimal */
            weight_kg?: string | null;
            sex?: components["schemas"]["SexEnum"] | components["schemas"]["BlankEnum"];
            is_sterilized?: boolean;
            /** Format: date */
            vaccinations_valid_until?: string | null;
            /** Format: date */
            deworming_valid_until?: string | null;
            notes?: string;
        };
        /** @description Validate garden create/update. ``host``/status/photos are set elsewhere (PLAN 8.2). */
        PatchedGardenWrite: {
            title?: string;
            description?: string;
            city?: string;
            address?: string;
            /** Format: decimal */
            latitude?: string;
            /** Format: decimal */
            longitude?: string;
            area_m2?: number;
            surface_type?: components["schemas"]["SurfaceTypeEnum"] | components["schemas"]["BlankEnum"];
            is_fenced?: boolean;
            /** Format: decimal */
            fence_height_m?: string | null;
            max_dogs?: number;
            /** Format: decimal */
            price_per_hour?: string;
            /** Format: time */
            open_from?: string;
            /** Format: time */
            open_to?: string;
            min_booking_hours?: number;
            amenities?: components["schemas"]["AmenitiesEnum"][];
            rules?: string[];
            is_active?: boolean;
        };
        /** @description Editable profile fields (PATCH /me/). ``role``/``email`` are intentionally excluded. */
        PatchedMeUpdate: {
            first_name?: string;
            last_name?: string;
            phone?: string;
            marketing_consent?: boolean;
        };
        /** @description Change password while authenticated (old + new + confirmation). */
        PatchedPasswordChange: {
            old_password?: string;
            new_password?: string;
            new_password_confirm?: string;
        };
        /** @description New gallery order: the full list of this garden's photo ids, cover first. */
        PatchedPhotoReorder: {
            photo_ids?: number[];
        };
        /** @description Validate a new client/host account (role limited, terms required, password confirmed). */
        Register: {
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            phone?: string;
            role: components["schemas"]["RegisterRoleEnum"];
            marketing_consent?: boolean;
            password: string;
            password_confirm: string;
            terms_accepted: boolean;
        };
        /**
         * @description * `client` - client
         *     * `host` - host
         * @enum {string}
         */
        RegisterRoleEnum: "client" | "host";
        /** @description Booking request body (PLAN 8.3). Domain validation happens in the service. */
        ReservationCreate: {
            garden: number;
            dog: number;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            /** @default 1 */
            dogs_count: number;
            /** @default  */
            message_to_host: string;
        };
        /** @description Full reservation view: price breakdown, message and all audit timestamps. */
        ReservationDetail: {
            readonly id: number;
            readonly status: components["schemas"]["StatusEnum"];
            readonly status_display: string;
            readonly garden: components["schemas"]["GardenMini"];
            readonly dog: components["schemas"]["DogMini"];
            readonly client: components["schemas"]["ClientMini"];
            readonly dogs_count: number;
            /** Format: date-time */
            readonly start_time: string;
            /** Format: date-time */
            readonly end_time: string;
            /** Format: decimal */
            readonly total_price: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly can_cancel: boolean;
            readonly can_pay: boolean;
            readonly can_accept: boolean;
            readonly can_reject: boolean;
            /** @description Whether cancelling right now would be refunded (the 24h policy, AD-5). */
            readonly refund_on_cancel: boolean;
            /** Format: decimal */
            readonly price_per_hour_snapshot: string;
            /** Format: decimal */
            readonly subtotal: string;
            /** Format: decimal */
            readonly service_fee: string;
            readonly message_to_host: string;
            /** Format: date-time */
            readonly expires_at: string | null;
            /** Format: date-time */
            readonly paid_at: string | null;
            /** Format: date-time */
            readonly decided_at: string | null;
            /** Format: date-time */
            readonly cancelled_at: string | null;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Light row for the client/host panels (PLAN 8.2). */
        ReservationList: {
            readonly id: number;
            readonly status: components["schemas"]["StatusEnum"];
            readonly status_display: string;
            readonly garden: components["schemas"]["GardenMini"];
            readonly dog: components["schemas"]["DogMini"];
            readonly client: components["schemas"]["ClientMini"];
            readonly dogs_count: number;
            /** Format: date-time */
            readonly start_time: string;
            /** Format: date-time */
            readonly end_time: string;
            /** Format: decimal */
            readonly total_price: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly can_cancel: boolean;
            readonly can_pay: boolean;
            readonly can_accept: boolean;
            readonly can_reject: boolean;
            /** @description Whether cancelling right now would be refunded (the 24h policy, AD-5). */
            readonly refund_on_cancel: boolean;
        };
        /** @description Optional rejection reason forwarded to the client e-mail (PLAN 8.2). */
        ReservationReject: {
            /** @default  */
            reason: string;
        };
        /** @description One calendar event in the host schedule (PLAN 8.2). */
        ScheduleEvent: {
            readonly id: number;
            readonly garden_id: number;
            readonly garden_title: string;
            readonly dog_name: string;
            readonly client_name: string;
            /** Format: date-time */
            readonly start_time: string;
            /** Format: date-time */
            readonly end_time: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly status_display: string;
        };
        /**
         * @description * `male` - Samiec
         *     * `female` - Suka
         * @enum {string}
         */
        SexEnum: "male" | "female";
        /** @description One hourly availability slot (PLAN 8.3). */
        Slot: {
            hour: string;
            available: boolean;
        };
        /**
         * @description * `pending_payment` - Oczekuje na płatność
         *     * `awaiting_host` - Oczekuje na decyzję gospodarza
         *     * `confirmed` - Potwierdzona
         *     * `rejected` - Odrzucona
         *     * `cancelled` - Anulowana
         * @enum {string}
         */
        StatusEnum: "pending_payment" | "awaiting_host" | "confirmed" | "rejected" | "cancelled";
        /**
         * @description * `grass` - Trawa
         *     * `sand` - Piasek
         *     * `paved` - Utwardzona
         *     * `mixed` - Mieszana
         * @enum {string}
         */
        SurfaceTypeEnum: "grass" | "sand" | "paved" | "mixed";
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /** @description Public shape of the logged-in user returned by ``/me/`` and auth responses. */
        User: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly first_name: string;
            readonly last_name: string;
            readonly full_name: string;
            readonly phone: string;
            readonly role: components["schemas"]["UserRoleEnum"];
            readonly is_verified_host: boolean;
            /** Format: date-time */
            readonly verified_at: string | null;
            /** Format: date-time */
            readonly terms_accepted_at: string | null;
            readonly marketing_consent: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `client` - Klient
         *     * `host` - Gospodarz
         *     * `admin` - Administrator
         * @enum {string}
         */
        UserRoleEnum: "client" | "host" | "admin";
        /**
         * @description * `pending` - Oczekuje weryfikacji
         *     * `approved` - Zatwierdzony
         *     * `rejected` - Odrzucony
         * @enum {string}
         */
        VerificationStatusEnum: "pending" | "approved" | "rejected";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Logout"];
                "application/x-www-form-urlencoded": components["schemas"]["Logout"];
                "multipart/form-data": components["schemas"]["Logout"];
            };
        };
        responses: {
            /** @description No response body */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirm"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
        };
    };
    dogs_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDogListList"];
                };
            };
        };
    };
    dogs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DogWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["DogWrite"];
                "multipart/form-data": components["schemas"]["DogWrite"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogDetail"];
                };
            };
        };
    };
    dogs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogDetail"];
                };
            };
        };
    };
    dogs_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dogs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDogWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDogWrite"];
                "multipart/form-data": components["schemas"]["PatchedDogWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogDetail"];
                };
            };
        };
    };
    dogs_photo_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["DogPhoto"];
                "application/x-www-form-urlencoded": components["schemas"]["DogPhoto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogDetail"];
                };
            };
        };
    };
    gardens_list: {
        parameters: {
            query?: {
                amenities?: string;
                city?: string;
                date?: string;
                in_bbox?: string;
                max_dogs?: number;
                max_price?: number;
                min_area?: number;
                min_price?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /**
                 * @description * `grass` - Trawa
                 *     * `sand` - Piasek
                 *     * `paved` - Utwardzona
                 *     * `mixed` - Mieszana
                 */
                surface_type?: "grass" | "mixed" | "paved" | "sand";
                time_from?: string;
                time_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGardenListList"];
                };
            };
        };
    };
    gardens_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenDetail"];
                };
            };
        };
    };
    gardens_availability_retrieve: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD */
                date: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    host_gardens_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGardenListList"];
                };
            };
        };
    };
    host_gardens_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GardenWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["GardenWrite"];
                "multipart/form-data": components["schemas"]["GardenWrite"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenDetail"];
                };
            };
        };
    };
    host_gardens_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenDetail"];
                };
            };
        };
    };
    host_gardens_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    host_gardens_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedGardenWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedGardenWrite"];
                "multipart/form-data": components["schemas"]["PatchedGardenWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenDetail"];
                };
            };
        };
    };
    host_gardens_photos_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["GardenPhotoUpload"];
                "application/x-www-form-urlencoded": components["schemas"]["GardenPhotoUpload"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenPhoto"];
                };
            };
        };
    };
    host_gardens_photos_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                photo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    host_gardens_photos_reorder_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPhotoReorder"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPhotoReorder"];
                "multipart/form-data": components["schemas"]["PatchedPhotoReorder"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenPhoto"][];
                };
            };
        };
    };
    host_reservations_list: {
        parameters: {
            query?: {
                /** @description Restrict to one of the host's gardens. */
                garden?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /** @description Panel tab filter. */
                status_group?: "accepted" | "cancelled" | "completed" | "pending";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedReservationListList"];
                };
            };
        };
    };
    host_reservations_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationDetail"];
                };
            };
        };
    };
    host_reservations_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReservationReject"];
                "application/x-www-form-urlencoded": components["schemas"]["ReservationReject"];
                "multipart/form-data": components["schemas"]["ReservationReject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationDetail"];
                };
            };
        };
    };
    host_schedule_list: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD (inclusive). */
                from: string;
                /** @description Restrict to one of the host's gardens. */
                garden?: number;
                /** @description YYYY-MM-DD (inclusive). */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEvent"][];
                };
            };
        };
    };
    host_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostStats"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMeUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMeUpdate"];
                "multipart/form-data": components["schemas"]["PatchedMeUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me_password_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPasswordChange"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPasswordChange"];
                "multipart/form-data": components["schemas"]["PatchedPasswordChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    reservations_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /** @description Panel tab filter. */
                status_group?: "cancelled" | "completed" | "upcoming";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedReservationListList"];
                };
            };
        };
    };
    reservations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["ReservationCreate"];
                "multipart/form-data": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationDetail"];
                };
            };
        };
    };
    reservations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationDetail"];
                };
            };
        };
    };
    reservations_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResult"];
                };
            };
        };
    };
    "reservations_export.csv_retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
}
