"""Project-wide pytest fixtures.

Keeps the whole suite off the real media volume: any test that produces a file — uploaded
photos or, since B6, the invoice PDFs generated by ``seed_demo`` — writes into a per-test
temp directory instead of ``backend/media``. Apps that predate this (gardens, reservations)
define their own ``_tmp_media``; pytest treats those as local overrides of this one, so the
behaviour is identical and exactly one fixture runs per test.
"""

import pytest


@pytest.fixture(autouse=True)
def _tmp_media(settings, tmp_path):
    """Redirect ``MEDIA_ROOT`` to a throwaway per-test directory."""
    settings.MEDIA_ROOT = str(tmp_path / "media")
