# Generated by Django 5.2.15 on 2026-06-13 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('area_m2', models.PositiveIntegerField()),
                ('surface_type', models.CharField(blank=True, choices=[('grass', 'Trawa'), ('sand', 'Piasek'), ('paved', 'Utwardzona'), ('mixed', 'Mieszana')], max_length=6)),
                ('is_fenced', models.BooleanField(default=True)),
                ('fence_height_m', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('max_dogs', models.PositiveSmallIntegerField(default=1)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=7)),
                ('open_from', models.TimeField(default='08:00')),
                ('open_to', models.TimeField(default='20:00')),
                ('min_booking_hours', models.PositiveSmallIntegerField(default=1)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(choices=[('pending', 'Oczekuje weryfikacji'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony')], db_index=True, default='pending', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GardenPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gardens/%Y/%m/')),
                ('thumbnail', models.ImageField(upload_to='gardens/%Y/%m/')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gardens.garden')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='garden',
            index=models.Index(fields=['city', 'verification_status', 'is_active'], name='garden_city_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='garden',
            constraint=models.CheckConstraint(condition=models.Q(('open_to__gt', models.F('open_from'))), name='garden_open_to_after_open_from'),
        ),
        migrations.AddConstraint(
            model_name='garden',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_hour__gt', 0)), name='garden_price_per_hour_positive'),
        ),
    ]
