# Generated by Django 5.2.15 on 2026-06-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='pln', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('succeeded', 'Opłacona'), ('failed', 'Nieudana'), ('refunded', 'Zwrócona')], db_index=True, default='pending', max_length=12)),
                ('billing_name', models.CharField(blank=True, max_length=120)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_address', models.CharField(blank=True, max_length=200)),
                ('billing_postal_code', models.CharField(blank=True, max_length=12)),
                ('billing_city', models.CharField(blank=True, max_length=80)),
                ('billing_country', models.CharField(default='PL', max_length=2)),
                ('billing_company', models.CharField(blank=True, max_length=160)),
                ('tax_id', models.CharField(blank=True, max_length=15)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
